# Generated by Django 5.1.1 on 2024-10-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiсker', models.CharField(max_length=50)),
                ('lastprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timeframe', models.IntegerField()),
                ('dateevent', models.DateTimeField()),
            ],
        ),
    ]
