# Generated by Django 5.1.2 on 2024-10-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='dateevent',
            field=models.DateTimeField(auto_now_add=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='data',
            name='timeframe',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='data',
            name='tiсker',
            field=models.CharField(max_length=10),
        ),
    ]
