# Generated by Django 5.1.2 on 2024-10-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_data_tiсker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='tiсker',
        ),
        migrations.AddField(
            model_name='data',
            name='ticker',
            field=models.CharField(default='BTC', max_length=10),
        ),
        migrations.AlterField(
            model_name='data',
            name='lastprice',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='data',
            name='timeframe',
            field=models.IntegerField(),
        ),
    ]
